### ISSUE TITLE
NameError: name 'contextoutput' is not defined

### ISSUE THREAD

**Issue by NoOne-hub** [jerdna-regeiz/splitmind#1]
When i open tmux and gdb myfile，it doesn't work. The title is my output

**Comment by jerdna-regeiz** [comment]
Are you using the latest dev branch of pwndbg? It requires the context splitting feature

**Comment by NoOne-hub** [comment]
> Are you using the latest dev branch of pwndbg? It requires the context splitting feature

Of course,I use the command "git clone https://github.com/pwndbg/pwndbg" recently.

**Comment by NoOne-hub** [comment]
I try to find out where is contextoutput in pwndbg,but i cann't find it.Can you tell me where is it?Maybe I can solve it myself

**Comment by jerdna-regeiz** [comment]
Sure: https://github.com/pwndbg/pwndbg/blob/64ca9a66cf5b8d1a07cae2975fcc4b471650efd8/pwndbg/commands/context.py#L146

**Comment by NoOne-hub** [comment]
> Sure: https://github.com/pwndbg/pwndbg/blob/64ca9a66cf5b8d1a07cae2975fcc4b471650efd8/pwndbg/commands/context.py#L146

Thanks for that,I found the problem.I install the stable version and it doesn't have this, the dev version have this.

**Comment by NoOne-hub** [comment]
After that,I start it successfully. Thanks again for your kind help

**Comment by Marsel-marsel** [comment]
I am also have this issue, despite of I am using the latest pwndbg (dev) and splitmd (master) branches. I digging into a little bit and figured out that problem is in _splitmind/splitmind/thinker/pwndbg.py_ `import pwndbg`:
```
try:
     import pwndbg
     from pwndbg.commands.context import contextoutput, output, clear_screen
except ImportError as err:
     # Most likely not run from gdb but something else..
     pass
```
`ImportError` suppressed and `contextoutput()` is not initialized.
