### ISSUE TITLE
of="main" not working

### ISSUE THREAD

**Issue by ale-ben** [jerdna-regeiz/splitmind#2]
I installed Pwndbg (dev) and splitmind today cloning dev branch for Pwndbg and master for splitmind.

**Environment**
macOS Catalina 10.15.3
Docker Engine 19.03.5
Docker Desktop 2.2.0.3

Dockerfile:
 ```
FROM ubuntu
RUN apt update 
RUN apt upgrade -y
RUN apt install -y \
    vim \
    exiv2 \
    imagemagick \
    binutils \
    wget \
    gdb \
    ltrace \
    strace \
    git \
    gcc \
    gdb \
    tmux \
    locales

# Set the locale
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8 

ENTRYPOINT ["/bin/bash"]
```

**Setup 1**
Following your documentation:
```
python
import splitmind
(splitmind.Mind()
  .below(display="backtrace")
  .right(display="stack", cmd="grep rax", use_stdin=True)
  .right(display="regs")
  .below(cmd='sleep 1; htop')
  .below(of="stack", cmd='sleep 1; watch ls')
  .right(of="main", display="disasm")
  .show("legend", on="disasm")
).build()
end
```

[Here is how gdb is splitting things in Setup 1](https://ibb.co/z4Vv8Gc)
[And here is my .gdbinit for Setup 1](https://ibb.co/HXjwfcZ)

**Setup 2**
Following [Pwndbg's example](https://github.com/pwndbg/pwndbg/blob/dev/FEATURES.md)
```
python
import splitmind
(splitmind.Mind()
  .tell_splitter(show_titles=True)
  .tell_splitter(set_title="Main")
  .right(display="backtrace", size="25%")
  .above(of="main", display="disasm", size="80%", banner="top")
  .show("code", on="disasm", banner="none")
  .right(cmd='tty; tail -f /dev/null', size="65%", clearing=False)
  .tell_splitter(set_title='Input / Output')
  .above(display="stack", size="75%")
  .above(display="legend", size="25")
  .show("regs", on="legend")
  .below(of="backtrace", cmd="ipython", size="30%")
).build(nobanner=True)
end
```

[Here is how gdb is splitting things in Setup 2](https://ibb.co/C84grjy)
[And here is my .gdbinit for Setup 2](https://ibb.co/9q6xyH0)

**Problems**
1) `.right(of="main", display="disasm")` if I'm correct should split right of the main pane with a pane named disasm but it doesn't, it seems that of="main" does not work (while of="stack" in Example 1 does). Same thing happens in Example 2 
2) `.below(of="backtrace", cmd="ipython", size="30%")` in Example 2 does nothing (I think)

Am I doing anything wrong?
Am I missing any config or step?

**Comment by jerdna-regeiz** [comment]
I have a clue. Will try it later today!

**Comment by jerdna-regeiz** [comment]
Okay, I got it's trail.
It is a different behavior between tmux 2.6 and later versions (at least 2.8+).
When splitting 2.8 does not give the focus to the target pane, but 2.6 does.
I'll look into it if I can easily support both.
