### ISSUE TITLE
TMUX_PANE is not set

### ISSUE THREAD

**Issue by choffmann** [jerdna-regeiz/splitmind#3]
I have the problem that environment variable TMUX_PANE should be set. However, I don't know to what?

![image](https://user-images.githubusercontent.com/1169481/76764846-d506c480-6795-11ea-94f8-63474fbb33c1.png)

**Comment by choffmann** [comment]
Ok, understood. You have to run tmux and start gdb in there. Maybe include this information in your README.

**Comment by jerdna-regeiz** [comment]
Better: it should check if run in TMUX and disable itself if not. :)
