### ISSUE TITLE
How to adjust pane size created by show() method?

### ISSUE THREAD

**Issue by soaringk** [jerdna-regeiz/splitmind#6]
I was tracing a simple program with debugging info. And it seemed that the disasm section was too long to display the source code. Any method I can reduce the number of lines of source code or assembly instruction?

<img width="1792" alt="Screen Shot 2020-07-26 at 12 25 11 AM" src="https://user-images.githubusercontent.com/42689402/88461581-5ce4a400-ced7-11ea-885f-6ccb658e4aae.png">

<img width="1792" alt="Screen Shot 2020-07-26 at 12 28 00 AM" src="https://user-images.githubusercontent.com/42689402/88461576-53f3d280-ced7-11ea-9684-5d7979f2f8b0.png">

**Comment by bjorn3** [comment]
You can specify the size of panes using the `size` parameter:

https://github.com/jerdna-regeiz/splitmind/blob/a95b50f308f6e78b15c1fae9ed11239a6b70bdb7/docs/examples/example1.gdbinit#L12

**Comment by soaringk** [comment]
I forgot to post my gdbinit file.

```
python
import splitmind
(splitmind.Mind()
  .tell_splitter(show_titles=True)
  .tell_splitter(set_title="Main")
  .below(display="backtrace", size="18%")
  .left(of="main", display="disasm", size="72%", banner="top")
  .show("code", on="disasm", banner="none")
  .right(cmd='tty; tail -f /dev/null', size="55%", clearing=False)
  .tell_splitter(set_title='Input / Output')
  .above(display="stack", size="75%")
  .above(display="legend", size="20")
  .show("regs", on="legend")
  .right(of="backtrace", cmd="ipython3", size="70%")
).build(nobanner=True)
end
set context-sections  "regs args code disasm stack backtrace"
set context-code-lines 30
set context-source-code-lines 30
```

I found out this two lines were creating much more lines than I needed.
```
set context-code-lines 30
set context-source-code-lines 30
```

Thanks for your reply.

**Comment by soaringk** [comment]
There seems to be no option of `size` in `show` method?
