### ISSUE TITLE
Scroll up and down asm and stack pane

### ISSUE THREAD

**Issue by gaetanww** [jerdna-regeiz/splitmind#7]
First, of all, thanks for your work on this project. It's been very helpful!

Just one question:
In `gdb -tui` I could scroll up the `asm` window using the arrow keys and PgUp, PgDown. Is it possible to do it with splitmind? When using the arrow keys while focusing on the `asm` pane, I get the following output: `^[[A^[[A^[[A^[[A^[[A^[[A^[[A`.

If there's a solution for the `asm` window, is there also a similar solution for the `stack` window?

**Comment by jerdna-regeiz** [comment]
Sadly this is not possible in the current architecture, as the input is only piped to tty devices. I do not control any input on those tty or rather console itself.

But you should be able to utilize tmux itself, as it already includes scrolling the buffer. Depending on your tmux config you can try page-up and -down.
